#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the controlled release/train_guard.py single-file candidate."""

from __future__ import annotations

import ast
import sys
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
SRC_PKG = ROOT / "src" / "train_guard"
OUT = ROOT / "release" / "train_guard.py"

ORDER = [
    "__init__.py",
    "core/exitcodes.py",
    "core/optional.py",
    "core/privacy.py",
    "core/io_util.py",
    "core/config.py",
    "core/events.py",
    "core/__init__.py",
    "adapters/base.py",
    "adapters/generic.py",
    "adapters/huggingface.py",
    "adapters/__init__.py",
    "report/html.py",
    "report/__init__.py",
    "data/cache.py",
    "data/commands.py",
    "data/__init__.py",
    "run/commands.py",
    "run/__init__.py",
    "env/doctor.py",
    "env/__init__.py",
    "eval/metrics.py",
    "eval/__init__.py",
    "cli.py",
    "__main__.py",
]


def module_name(rel: str) -> str:
    """Map relative path to module name under train_guard."""
    p = Path(rel)
    if p.name == "__init__.py":
        parts = list(p.parts[:-1])
    else:
        parts = list(p.with_suffix("").parts)
    return "train_guard" + (("." + ".".join(parts)) if parts else "")


def main() -> int:
    """Bundle package sources into a self-contained launcher."""
    sources = {}
    for rel in ORDER:
        path = SRC_PKG / rel
        if not path.exists():
            print(f"skip missing {rel}", file=sys.stderr)
            continue
        sources[module_name(rel)] = path.read_text(encoding="utf-8")

    for path in sorted(SRC_PKG.rglob("*.py")):
        rel = str(path.relative_to(SRC_PKG)).replace("\\", "/")
        name = module_name(rel)
        if name not in sources:
            sources[name] = path.read_text(encoding="utf-8")

    for name, src in sources.items():
        try:
            ast.parse(src)
        except SyntaxError as exc:
            print(f"Syntax error in {name}: {exc}", file=sys.stderr)
            return 1

    payload = repr(sources)
    header = dedent(
        '''
        #!/usr/bin/env python3
        # -*- coding: utf-8 -*-
        # AUTO-GENERATED by scripts/bundle_singlefile.py — DO NOT EDIT.
        # Source of truth: src/train_guard/
        """Train Guard single-file distribution."""

        from __future__ import annotations

        import importlib.util
        import sys
        from types import ModuleType

        _MODULES = __PAYLOAD__


        class _BundleLoader:
            """Load bundled modules from in-memory source."""

            def __init__(self, fullname: str, source: str) -> None:
                self.fullname = fullname
                self.source = source

            def create_module(self, spec):  # noqa: ANN001
                return None

            def exec_module(self, module: ModuleType) -> None:
                code = compile(self.source, "<bundle:" + self.fullname + ">", "exec")
                module.__file__ = "<bundle:" + self.fullname + ">"
                is_pkg = any(k.startswith(self.fullname + ".") for k in _MODULES) or self.fullname == "train_guard"
                if is_pkg:
                    module.__path__ = []  # type: ignore[attr-defined]
                    module.__package__ = self.fullname
                else:
                    module.__package__ = self.fullname.rpartition(".")[0] or self.fullname
                exec(code, module.__dict__)


        class _BundleFinder:
            """Meta path finder for bundled train_guard package."""

            def find_spec(self, fullname, path=None, target=None):  # noqa: ANN001
                source = _MODULES.get(fullname)
                if source is None:
                    if any(k.startswith(fullname + ".") for k in _MODULES):
                        source = ""
                    else:
                        return None
                loader = _BundleLoader(fullname, source)
                is_pkg = any(k.startswith(fullname + ".") for k in _MODULES) or fullname == "train_guard"
                return importlib.util.spec_from_loader(fullname, loader, is_package=is_pkg)


        def _install() -> None:
            # When this file is named train_guard.py, Python may register it as
            # module "train_guard" (non-package). Clear it so the bundled package loads.
            mod = sys.modules.get("train_guard")
            if mod is not None and not hasattr(mod, "__path__"):
                del sys.modules["train_guard"]
            sys.meta_path.insert(0, _BundleFinder())


        _install()

        from train_guard.cli import main  # noqa: E402

        if __name__ == "__main__":
            raise SystemExit(main())
        '''
    ).lstrip()
    header = header.replace("__PAYLOAD__", payload)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Modules bundled: {len(sources)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
